# -*- coding: utf-8 -*-
"""DreamScape.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mNydiPnHkHfpLEjN5VOuDebA8hQEc0FN
"""

import sys
import argparse
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
import string
import json

nltk.download('punkt_tab')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')

import os

nltk.data.path.append("/usr/local/nltk_data")  # Ensure it's looking in the right place
nltk.download('punkt', download_dir='/usr/local/nltk_data')  # Explicitly download



stop_words = set(stopwords.words("english"))

def preprocess(text):
    tokens = word_tokenize(text.lower())  # Lowercase & tokenize
    tokens = [word for word in tokens if word.isalpha()]  # Remove punctuation/numbers
    custom_stopwords = {"dream", "something", "like", "back", "felt"}
    stop_words.update(custom_stopwords)
    tokens = [word for word in tokens if word not in stop_words]  # Remove stopwords
    return " ".join(tokens)  # Join

parser = argparse.ArgumentParser()
parser.add_argument(
    "--text",
    type=str,
    required=True,
    help="The text to process",
)

import google.generativeai as genai
import os

# Set API key securely using an environment variable
os.environ["GOOGLE_API_KEY"] = "AIzaSyC-XukHCg6_neZVFz6fQyejY6F1m-fSM30"

# Configure the API
genai.configure(api_key=os.environ["GOOGLE_API_KEY"])

llm_model = genai.GenerativeModel("gemini-pro")

def get_mind_interpretations(text, model=llm_model):

  words = preprocess(text)

  prompt = f"""
  Here is a dream that has been processed using NLP: {words}. Can you provide an interpretation of this dream that
  that is focused on the mind and emotions. Do not format and just give plain text. Do not exceed 50 words in your
  response.
  """
  response = model.generate_content(prompt)
  return response.text

# get_mind_interpretations("I dreamt i won the lottery")

def get_spirit_interpretations(text, model=llm_model):
  words = preprocess(text)

  prompt = f"""
  Here is a dream that has been processed using NLP: {words}. Can you provide an interpretation of this dream that
  that is focused on the spirit aspect. Do not format and just give plain text. Do not exceed 50 words in your
  response.
  """
  response = model.generate_content(prompt)
  return response.text

# get_spirit_interpretations("I dreamt i won the lottery")

def get_action_interpretations(text, model=llm_model):
  words = preprocess(text)

  prompt = f"""
  Here is a dream that has been processed using NLP: {words}. Can you provide an task or an action to do to help with this dream
  or that relates to this dream. Do not format and just give plain text. Do not exceed 50 words in your
  response.
  """
  response = model.generate_content(prompt)
  return response.text

# get_action_interpretations("I dreamt i won the lottery")

def analyze_dream(text):
  result = {}
  result["mind"] = get_mind_interpretations(text)
  result["spirit"] = get_spirit_interpretations(text)
  result["action"] = get_action_interpretations(text)
  return result

dream_text = sys.argv[1]
# dream_text = "I dreamt i won the lottery"
result = analyze_dream(dream_text)

print(json.dumps(result))

