import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "DreamScape",
  description: "Generated by DreamScape",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <main
          className="relative flex items-center justify-center min-h-screen overflow-hidden bg-repeat bg-center"
          style={{
            backgroundImage: "url('/medieval-bricks.jpg')",
            backgroundSize: "400px 400px",
            backgroundBlendMode: "multiply",
            backgroundColor: "rgba(0,0,0,0.75)",
          }}
        >
          {children}
        </main>
      </body>
    </html>
  );
}
